### ISSUE TITLE
Build fails when I try to run the project

### ISSUE THREAD

**Issue by bruce-forte** [igor-baiborodine/vaadin-demo-bakery-app#1]
It says:

> Failed to execute goal com.vaadin:vaadin-maven-plugin:8.1.5:update-widgetset (default) on project vaadin-demo-bakery-app: Cval license check failed!: License for Vaadin Board 1 not found. Go to vaadin.com/pro for more details

The docs don't detail what to do.

**Comment by igor-baiborodine** [comment]
Hi Adam,
You need to create a Vaadin account and download Pro evaluation licenses here: https://vaadin.com/start/v8-full-stack-spring. 
Docs excerpt:
Please note: this full stack starter uses Vaadin Charts, Vaadin TestBench, Vaadin Board and Vaadin Designer. Before you can run your application, you need to install licenses for all of these products.

**Comment by igor-baiborodine** [comment]
Please create a Vaadin account and download Pro evaluation licenses here: https://vaadin.com/start/v8-full-stack-spring.
