### ISSUE TITLE
Excuse me，Ask you a question

### ISSUE THREAD

**Issue by BradyYue** [igor-baiborodine/vaadin-demo-bakery-app#3]
I downloaded the demo.springboot version, but when it is executed, it is displayed on the dashboard. "Widgetset 'com.vaadin.DefaultWidgetSet' does not contain an implementation for com.vaadin.board.Board. Check the connector's @Connect mapping, the widgetset's GWT module description file and re-compile your widgetset. In case you have downloaded a vaadin add-on package, you might want to refer to"，
Is there a good solution? thank you very much

**Comment by igor-baiborodine** [comment]
Hi, which version of Vaadin/Service Pack did you use?
