### ISSUE TITLE
admin views not being protected from other roles

### ISSUE THREAD

**Issue by cemivb** [igor-baiborodine/vaadin-demo-bakery-app#4]
I have been checking your bakery application for reference about using spring security + vaadin, and I think the admin views (users and products) aren't being protected.

If you log in as barista, you can't see the menu items since you don't add them in the AppRouterLayout, but if you type in the url bar /products or /users, you can go to those pages as barista and edit the information. According to the role, barista shouldnt be able to see these pages.

I don't know if this is exactly an issue, or its the desired behaviour for the application. Regardless of that, very good job.

**Comment by igor-baiborodine** [comment]
I can't take credit for this application. Vaadin developped this demo app. I only generated the source code by using their starter pack and checked in to my GitHub account for my convinience.

**Comment by cemivb** [comment]
Sorry, I messed up with the repositories and I thought this was the official one from Vaadin. You can delete this issue as this doesnt belong here, plus the thing I mentioned has been already fixed in the newest bakery starter
