### ISSUE TITLE
Failed to retrieve RMIServer

### ISSUE THREAD

**Issue by joaoLevy** [igor-baiborodine/vaadin-demo-bakery-app#6]
Hello Igor,

I downloaded the branch v14 and after running mvn com.github.eirslett:frontend-maven-plugin:1.7.6:install-node-and-npm -DnodeVersion="v12.14.0" as requested by vaadin maven plugin I runned mvn clean package and mvn verify -Pit. This gave me the following exception:
- Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.2.1.RELEASE:start (pre-integration-test) on project vaadin-demo-bakery-app: Could not contact Spring B
oot application: Failed to retrieve RMIServer stub: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: non-JRMP server at remote endpoint]
Did i do something wrong or is this an issue in the project?

Greetings, João Levy

**Comment by igor-baiborodine** [comment]
Hi João,

Please try again. It should be working now. I reverted the last commit, which upgraded the vaadin-bom version.

Thanks,

Igor

**Comment by joaoLevy** [comment]
Hi Igor, I deleted the project, cloned the project and tried again but still gave me the same error. Thank you very much for your attention.

Best regards,
João Levy

**Comment by igor-baiborodine** [comment]
João,

Are you able to start the app with mvn spring-boot:run?
Do you use an IDE? 
What OS: Windows or Linux?

Thanks,

Igor

**Comment by joaoLevy** [comment]
Are you able to start the app with mvn spring-boot:run? Yes
Do you use an IDE? Yes, Intellij
What OS: Windows or Linux? Windows 10

Thank you very much,
João

**Comment by igor-baiborodine** [comment]
It works for me in IntelliJ on Ubuntu 18.04 with JDK 8_251:
Here is the launch command generated by IntelliJ:

`/home/igor/Programs/Java/jdk1.8.0_251/bin/java -Dmaven.multiModuleProjectDirectory=/home/igor/GitRepos/vaadin-demo-bakery-app -Dmaven.home=/home/igor/Programs/idea-IU-193.6911.18/plugins/maven/lib/maven3 -Dclassworlds.conf=/home/igor/Programs/idea-IU-193.6911.18/plugins/maven/lib/maven3/bin/m2.conf -Dmaven.ext.class.path=/home/igor/Programs/idea-IU-193.6911.18/plugins/maven/lib/maven-event-listener.jar -javaagent:/home/igor/Programs/idea-IU-193.6911.18/lib/idea_rt.jar=34917:/home/igor/Programs/idea-IU-193.6911.18/bin -Dfile.encoding=UTF-8 -classpath /home/igor/Programs/idea-IU-193.6911.18/plugins/maven/lib/maven3/boot/plexus-classworlds.license:/home/igor/Programs/idea-IU-193.6911.18/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar org.codehaus.classworlds.Launcher -Didea.version2020.1.1 verify -Pit`

**Comment by joaoLevy** [comment]
Sorry for the late answer, I have JDK 12 but I am limiting it in the pom to 8 and the vaadin bom version is at 14.1.17. I will try it by substituting the JDK 12 with the JDK 8.

**Comment by joaoLevy** [comment]
Hello Igor,

So I tried with java 8 and after running the unit tests it is still giving me this exception:
Caused by: java.rmi.ConnectIOException: non-JRMP server at remote endpoint

Might there be some environment issues that could cause this exception?

**Comment by joaoLevy** [comment]
So I added <forked>false</false> to the spring maven plugin and it worked. I don't know if this shouldn't be the case.

**Comment by igor-baiborodine** [comment]
Great. I'm closing the issue.
